### ISSUE TITLE
[Feat] ShortcutCell subtitle 조절

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MacC-Team-HappyAnding#323]
## 필요한 기능
- Shortcut cell Subtitle의 frame 조절 필요
  - 충분한 공간이 있음에도 불구하고, 줄바꿈이 되는 이슈 존재
 
## 해야 할 일 
- [x] #370

## 추가 컨텍스트
<img src = "https://user-images.githubusercontent.com/68676844/204126740-e0d81aa3-463a-435b-9777-cc6937912ed3.png" width = 250>

[stackoverflow](https://stackoverflow.com/questions/72685881/swiftui-text-doesnt-fit-full-width-while-having-multiple-lines)

**Comment by JIWON1923** [comment]
관련 이슈 스택오버플로우에도 있어서 넣어놨어요!

**Comment by HanGyeongjun** [comment]
swiftui에서 해당 이슈를 정식으로 해결하는 방법이 없어서 차선책으로 subtitle text 뒤에 공백을 8개 넣는 방식으로 해결했습니다
