### ISSUE TITLE
[Refactor] 강제언래핑 없애기

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MacC-Team-HappyAnding#339]
## 필요한 기능
- ReadshortcutView에서 shortcut이 강제언래핑되어 사용되고 있습니다.
- nil인지 확인 후 강제언래핑을 진행하고있으나, 바인딩 값이 nil로 변경될 가능성이 존재하기 때문에 (기능상에서는 없을 것 같긴 해요) 리팩토링이 필요합니다.

## 해야 할 일 
- [ ] 강제언래핑 없애기

**Comment by HanGyeongjun** [comment]
이후 리팩토링 과정에서 해결된 이슈이므로 Close합니다.
