### ISSUE TITLE
[Fix] Navigation Link가 작동하지 않는 문제

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MacC-Team-HappyAnding#380]
## 버그 설명
- swipe 제스처를 취소했을 때, 네비게이션 링크가 동작하지 않습니다.

## 접근 단계
- 특정 화면으로 들어갑니다. (저는 카테고리로 들어갔어요)
- 스와이프 제스처를 이용해 뒤로가는 척! 을 합니다.
- 이후 네비게이션 링크가 작동하지 않습니다

## Screenshot
https://user-images.githubusercontent.com/68676844/216615544-9311d58e-22d4-475b-a8b5-e2b48c059898.mov

**Comment by JIWON1923** [comment]
해당 이슈 시뮬레이터 iOS16.2버전 기준으로 정상 작동하는 것 확인했습니다. (iOS16은 시뮬에서도 동작 안 함)
Navigation Stack 이슈 같은데, 정확한 정보 더 찾아보고 정보 공유하도록 하겠습니다!

**Comment by HanGyeongjun** [comment]
실기기(iPhone 11 Pro) iOS 16.2 및 16.3 환경에서 정상 작동 확인했습니다!
확실히 iOS16 초기 버전에서 있던 Navigation Stack 버그가 맞는 것 같네요🤔
