### ISSUE TITLE
[Fix] 댓글 입력 시 무제한 줄바꿈 가능으로 인한 레이아웃 오류

### ISSUE THREAD

**Issue by HanGyeongjun** [DeveloperAcademy-POSTECH/MacC-Team-HappyAnding#383]
## 버그 설명
- 현재 댓글 및 답글 입력창의 무제한 줄바꿈이 가능해서 댓글 입력 레이아웃에 대한 오류가 존재합니다.

## 접근 단계
- ShortcutDetailView의 댓글 입력창으로 접근 
- 댓글 및 답글 입력 시 무제한 줄바꿈이 가능함
- 이로 인한 레이아웃 오류 존재

## 정상 작동 결과
- 줄바꿈은 가능하되, 레이아웃을 해치치 않는 정도의 줄바꿈을 넘어가면 더 이상 댓글의 textfield가 늘어나지 않도록 처리합니다.
- 해당 textfield 내에서 스크롤이 가능하도록 처리합니다.

## Screenshot

https://user-images.githubusercontent.com/94854258/216680255-011f9773-95f2-4f97-a5b7-e96ffd35419e.MP4

## 추가 컨텍스트
- 현재 댓글에 대한 글자수 제한도 없기 때문에 해당 버그 해결과 함께 댓글 글자 수 제한도 함께 논의해보면 좋을 것 같습니다.

**Comment by JIWON1923** [comment]
저는 댓글에는 글자 수 제한이 없어도 된다고 생각합니다!
(보통 제한 없는 경우가 많지 않나요?)

**Comment by HanGyeongjun** [comment]
> 저는 댓글에는 글자 수 제한이 없어도 된다고 생각합니다! (보통 제한 없는 경우가 많지 않나요?)

일반적으로는 글자 수 제한이 없지만, 모바일 환경에서 과도한 줄바꿈이 들어간 댓글이 달릴 경우 사용자가 오류라고 인식할 수 있다고 생각해서 이에 관한 대책이 있는 것이 괜찮겠다는 생각이었습니다! 다른 분들은 어떠신가요? 글자 수 제한이 아닌 다른 대안도 좋습니다 👍

**Comment by JIWON1923** [comment]
> > 저는 댓글에는 글자 수 제한이 없어도 된다고 생각합니다! (보통 제한 없는 경우가 많지 않나요?)
> 
> 일반적으로는 글자 수 제한이 없지만, 모바일 환경에서 과도한 줄바꿈이 들어간 댓글이 달릴 경우 사용자가 오류라고 인식할 수 있다고 생각해서 이에 관한 대책이 있는 것이 괜찮겠다는 생각이었습니다! 다른 분들은 어떠신가요? 글자 수 제한이 아닌 다른 대안도 좋습니다 👍

그렇다면 개행문자가 연속으로 3개 이상 작성되지 못하도록 제한을 두는 건 어떨까요?
2개인 이유는 가독성의 이유로 보통 1~2개의 개행문자는 허용해도 된다고 생각해서요!

그렇다면 과도한 줄바꿈 문제는 해결될 수 있을 것 같아요

**Comment by HanGyeongjun** [comment]
> 그렇다면 개행문자가 연속으로 3개 이상 작성되지 못하도록 제한을 두는 건 어떨까요? 2개인 이유는 가독성의 이유로 보통 1~2개의 개행문자는 허용해도 된다고 생각해서요!
> 
> 그렇다면 과도한 줄바꿈 문제는 해결될 수 있을 것 같아요

저는 찬성입니다!
