### ISSUE TITLE
[Feat] 단축어 및 추천 모음집 업로드 모달 타입 변경 (Apple Feedback)

### ISSUE THREAD

**Issue by HanGyeongjun** [DeveloperAcademy-POSTECH/MacC-Team-HappyAnding#424]
## 필요한 기능
- 2023.03.10 진행한 Kyle과의 Design Feedback을 통해 개선 피드백을 받은 사항입니다.
- 단축어 및 추천 모음집 업로드 모달의 형태를 변경합니다.
- FullScreenCover -> Modal

## 해야 할 일 
- [ ] 단축어 및 추천 모음집 업로드 모달의 형태를 변경합니다.

## 스크린샷
|추천 모읍집 업로드|단축어 업로드|
|---|---|
![Simulator Screen Shot - iPhone 14 Pro - 2023-03-13 at 10 51 32](https://user-images.githubusercontent.com/94854258/224590528-885c31ea-17ba-4671-86c7-c586e1a821b1.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-03-13 at 10 51 19](https://user-images.githubusercontent.com/94854258/224590509-bd3d45a9-539b-4c79-823e-43f150bea54f.png)|

**Comment by JIWON1923** [comment]
## 3/27 회의

### 모달을 사용하는 이유
- 글 작성 단계에서 취소를 손 쉽게 하기 위해서라고 생각한다.

### 적용하지 않는 이유
- 모달에서 Navigation을 사용하는 것이 어색하다. (우리는 모달 내부에 모달을 띄울 수 없다)
- ProgressView의 표기도 어색해질 것이라고 생각한다.
- 모달에서 글 작성 후 취소를 하게 되면, 취소에 대한 alert 작업이 추가된다. 이것이 편한 UX를 제공하는 것은 아니라고 생각한다.
- 모달 내부에서 Navigation을 사용하는 레퍼런스 찾아보고, 논의 후에 적용하자

### 앞으로 고려할 점
- 현재 글 작성할 때 취소 버튼 클릭 시, Alert를 띄워야할까에 대한 레퍼런스를 찾아보자.
