### ISSUE TITLE
[Feat] App 이름 변경

### ISSUE THREAD

**Issue by JIWON1923** [DeveloperAcademy-POSTECH/MacC-Team-HappyAnding#55]
## 필요한 기능
- 현재 팀 이름으로 되어있는 앱 이름을 ShortcutsZip으로 바꿔주세요

## 추가 컨텍스트
- App store 배포시 타이틀은 ShortcutsZip : 단축어모음집로 설정해야합니다!

**Comment by HanGyeongjun** [comment]
#106 함께 변경 완료했습니다!
